fieldLayouts:
  55b472ee-d23c-417e-acbb-e24158eb9cf3:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 3a85e216-c039-460f-8e3e-6016da1a2d3a
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 90619285-e728-461d-aabd-7bf789279798 # Modules
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 186ef2da-dcc8-4048-a88f-4aae49ed3226
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 2e3f2bf4-b42b-4250-a5ad-dbe3aece952c
        userCondition: null
handle: homepage
hasTitleField: false
name: Homepage
section: 7aa67058-a1f3-46ad-8a6b-4cc480137301 # Homepage
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
sortOrder: 1
titleFormat: '{section.name|raw}'
titleTranslationKeyFormat: null
titleTranslationMethod: site
