baseUrl: $PRIMARY_SITE_URL
handle: default
hasUrls: true
language: en-US
name: 'Tecumseh Boilerplate'
primary: true
siteGroup: 0d3b124c-a22c-492b-905d-244d625e5e84 # Tecumseh Boilerplate
sortOrder: 1
